// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiFruCrVaxEpRtZnHIJsvfvP0VIro84XI',
    appId: '1:1087176807182:web:c2b8fa822fb65cfe5bfd5f',
    messagingSenderId: '1087176807182',
    projectId: 'enomapp-c0b54',
    authDomain: 'enomapp-c0b54.firebaseapp.com',
    storageBucket: 'enomapp-c0b54.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeljuDTd3ZI2u6_6KPs85xQZVITK-0HEI',
    appId: '1:1087176807182:android:cb2c96a7e5cf79c85bfd5f',
    messagingSenderId: '1087176807182',
    projectId: 'enomapp-c0b54',
    storageBucket: 'enomapp-c0b54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1KhtHF-2iPizms6og6YGAqvI0KLmx_Go',
    appId: '1:1087176807182:ios:ed7e929b1ddab8ac5bfd5f',
    messagingSenderId: '1087176807182',
    projectId: 'enomapp-c0b54',
    storageBucket: 'enomapp-c0b54.firebasestorage.app',
    iosBundleId: 'com.enom.enomApp',
  );
}
