// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzu4tcxeczP7fd8DuhFx8hAhK9zxt9rps',
    appId: '1:241964969065:web:9aa7584385bf50147746f8',
    messagingSenderId: '241964969065',
    projectId: 'enomai',
    authDomain: 'enomai.firebaseapp.com',
    storageBucket: 'enomai.firebasestorage.app',
    measurementId: 'G-QGTMPC5NVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxp-YFyAEI-2G3p2A0X6AOdljkkA93HqY',
    appId: '1:241964969065:android:f1a2a8ec86028e1c7746f8',
    messagingSenderId: '241964969065',
    projectId: 'enomai',
    storageBucket: 'enomai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1vTGb_AhJz9PqHak66qRCmpMqqfmUuGQ',
    appId: '1:241964969065:ios:1f6dec927def72387746f8',
    messagingSenderId: '241964969065',
    projectId: 'enomai',
    storageBucket: 'enomai.firebasestorage.app',
    iosBundleId: 'com.enom.enomApp',
  );

}